import { Wheat, Loader2, Trash2, Lightbulb, Upload, Settings, MessageSquare, Send, Camera, Info, Home, LayoutDashboard, Tractor, BarChart3, BookOpen, Leaf, Thermometer, Wind, Droplets, AlertTriangle, ChevronRight, Map, Sprout, Satellite, PlusCircle, X, Donut, History, RefreshCw, Mic, MicOff, Store, Headphones } from 'lucide-react';

export const Icons = {
  logo: Wheat,
  spinner: Loader2,
  trash: Trash2,
  solution: Lightbulb,
  upload: Upload,
  settings: Settings,
  messagesquare: MessageSquare,
  send: Send,
  camera: Camera,
  info: Info,
  home: MessageSquare,
  dashboard: LayoutDashboard,
  tractor: Tractor,
  insights: BarChart3,
  resources: BookOpen,
  sustainability: Leaf,
  thermometer: Thermometer,
  wind: Wind,
  droplets: Droplets,
  alert: AlertTriangle,
  chevronRight: ChevronRight,
  map: Map,
  sprout: Sprout,
  satellite: Satellite,
  plusCircle: PlusCircle,
  x: X,
  chartDonut: Donut,
  history: History,
  refresh: RefreshCw,
  mic: Mic,
  micOff: MicOff,
  market: Store,
  headphones: Headphones,
};
